# See https://starship.rs/config/ for more informations

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[âœ](bold green)'
error_symbol = "[âœ–](bold red) "

[directory]
style = "bold cyan"
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_commit]
style = "bold white"

[git_status]
conflicted = "âŒ ${count} "
ahead = "ğŸ”¼ ${count} "
behind = "ğŸ”½ ${count} "
diverged = "â‡„ ${count} "
untracked = "ğŸ¤· "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[nodejs]
format = "via [ğŸ¤– $version](bold green) "
